---
# Source: wordpress-proxy/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-nginxproxy
  id: 
  env: 
  labels:
    app: wp-nginxproxy-app
    env: dev
    id: C0901954
spec:
  selector:
    matchLabels:
      app: wp-nginxproxy-app
      env: dev
      id: C0901954
  replicas: 1
  template:
    metadata:
      labels:
        app: wp-nginxproxy-app
        env: dev
        id: C0901954
    spec:
      containers:
        - name: wp-nginxproxy
          image: bhavanich11/nginx-custom:latest
          ports:
            - containerPort: 80
